### ISSUE TITLE
Questions about installation

### ISSUE THREAD

**Issue by GuangyuWang99** [Zerg-Overmind/Strivec#1]
Hi, thanks for sharing the wonderful work and the code! 

Here I have a small question regarding the installation. After installing `python=3.9` and `pytorch=1.10.1`, I get an error when running `python train_hier.py --config ./configs/TanksAndTemple/Family.txt` which raises:
**OSError: /home/miniconda3/envs/strivec/lib/python3.9/site-packages/torch/lib/../../../../libcurand.so.10: invalid ELF header**

What should I do to solve this?
Thanks in advance!

**Comment by Zerg-Overmind** [comment]
Hi, 
I've tried two different combinations: `python=3.9.13` with `torch.__version__=1.13.1`, and `python=3.7.6` with `torch.__version__=1.12.1`, which both work on my side (FYI). 

BTW，does the same error happen again on other scenes?

**Comment by GuangyuWang99** [comment]
Thanks for your quick reply. The issue is solved by using `python=3.9.13` with `torch.__version__=1.13.1`.
