### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by LiuShuai086** [Zerg-Overmind/Strivec#5]
Hi, I had a problem when I trained the program.

It was "Segmentation fault (core dumped)",  and I couldn't find feasible solution.

Could you give some instructions?

**Comment by Zerg-Overmind** [comment]
Hi, the problem was not witnessed on my side, could you please check your pytorch&cuda version?

**Comment by LiuShuai086** [comment]
Thanks for your prompt reply. My pytorch&cuda version is 2.0.1+cu117. And I have tried different pytorch&cuda version (e.g. torch==1.10.0 or torch==1.11.0 ), but the same error happened again. Sometimes the error would be 'Aborted (core dumped)'.

**Comment by Zerg-Overmind** [comment]
Hi, could you also try these [two combinations](https://github.com/Zerg-Overmind/Strivec/issues/1#issuecomment-1656575953)?
Cuz these two work for me.

**Comment by LiuShuai086** [comment]
I remove the conda environment and create it again, install the torch&cuda, then 'pip install' the module needed. Finally, it works. Maybe libraries incompatibility cause this problem.

**Comment by Zerg-Overmind** [comment]
glad
