### ISSUE TITLE
Different implement of Volume rendering compared to original nerf

### ISSUE THREAD

**Issue by ZhenhuiL1n** [Zerg-Overmind/Strivec#6]
Hi,

the raw2alpha implementation is different from the original nerf as shown below in the Cuda implementation.

![image](https://github.com/Zerg-Overmind/Strivec/assets/56009715/22d567c4-67bd-49bf-85ff-26e30707e8f5)

Could you please explain why it is implemented like this, thanks a lot!

**Comment by Zerg-Overmind** [comment]
Hi, sorry for my late reply. This is because we use softplus, which is also adopted in TensoRF. Again, we just want to do a fair comparison with TensoRF so we keep it the same.

alpha = 1 - exp(-softplus(density + shift) * interval)
              = 1 - exp(-log(1 + exp(density + shift)) * interval)
              = 1 - exp(log(1 + exp(density + shift)) ^ (-interval))
              = 1 - (1 + exp(density + shift)) ^ (-interval)

Best
